# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 07:22
from __future__ import unicode_literals

import API.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fucken', models.PositiveIntegerField(default=0, null=True)),
                ('typeApprove', models.PositiveIntegerField(default=0, null=True)),
                ('merchantToken', models.CharField(max_length=100, null=True)),
                ('callbackUrl', models.CharField(max_length=100, null=True)),
                ('costCounter', models.PositiveIntegerField(default=0, null=True)),
                ('merchantKey', models.CharField(default='4bd1a868ed1c4269b62f9ebdb6a691e5', max_length=100, null=True)),
                ('confidenceThreshold', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(max_length=100, null=True)),
                ('userID', models.CharField(max_length=100, null=True)),
                ('passwd', models.CharField(max_length=100, null=True)),
                ('requestID', models.CharField(max_length=100, null=True)),
                ('requestID_expire', models.PositiveIntegerField(default=0, null=True)),
                ('merchantInfo', models.TextField(null=True)),
                ('clientID', models.CharField(max_length=100, null=True)),
                ('clientGPS', models.CharField(max_length=100, null=True)),
                ('clientSensor', models.CharField(max_length=100, null=True)),
                ('completeTime', models.PositiveIntegerField(default=0, null=True)),
                ('frontPassportUploadFile', models.ImageField(null=True, upload_to=API.models.uploadPath)),
                ('backPassportUploadFile', models.ImageField(null=True, upload_to=API.models.uploadPath)),
                ('selfieUploadFile', models.ImageField(null=True, upload_to=API.models.uploadPath)),
                ('selfieImgCreated', models.DateTimeField(null=True)),
                ('callbackStatus', models.SmallIntegerField(null=True)),
                ('verifyResult', models.CharField(max_length=100, null=True)),
                ('idInfoSubmitted', models.TextField(null=True)),
                ('actionScript', models.CharField(max_length=100, null=True)),
                ('actionVid', models.FileField(null=True, upload_to=API.models.uploadPath)),
                ('actionReport', models.TextField(default="{'actionOrderMatch': 100, 'actionCodeMatch':1, 'score': 0, 'diff': 0, 'vidUploaded': 0}", null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
