# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20170619_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='actionReport',
            field=models.TextField(default="{'actionOrderMatch': 100, 'actionCodeMatch':100, 'score': 0, 'diff': 0, 'vidUploaded': 0}", null=True),
        ),
    ]
