# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20170622_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='verifyResult',
            new_name='verifyResultFromMS',
        ),
        migrations.AddField(
            model_name='upload',
            name='verifyAfterFilter',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
