# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_merchant_merchantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='actionResult',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
