# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_upload_actionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='merchantData',
        ),
        migrations.AddField(
            model_name='upload',
            name='merchantData',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
