# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20170803_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='fullName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='idNumber',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='issPlace',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='issused',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
